### PR TITLE
radsecproxy: Fix compile with glibc 2.34

### PR DESCRIPTION
**Pull request by hauke**
Maintainer: @tohojo 
Compile tested: archs (glibc)
Run tested: none

Description:

This backports a patch from upstream radsecproxy to fix compilation with glibc 2.34.

It fixes the following build problem:
radsecproxy.h:35:5: error: missing binary operator before token "("
   35 | #if PTHREAD_STACK_MIN > PTHREAD_STACK_SIZE
      |     ^~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:623: dtls.o] Error 1

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Review by tohojo — APPROVED** [review]
LGTM :)
