### PR TITLE
aria2: Fix faulty patch

### PR DESCRIPTION
**Pull request by neheb**
The if condition was wrong and caused compilation errors with 1.1.
Potentially broke 1.0.2.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

Maintainer: @kuoruan 
Compile tested: ramips

Description:
Some mixup between different versions of said patch.

### CODE REVIEW

**Comment by kuoruan** [comment]
@neheb  Please review this.
#7647

**Comment by kuoruan** [comment]
In the previous, we skip the openssl initialization when openssl version != 1.1, is that right?

**Comment by kuoruan** [comment]
But your new pr is:

```cc
#if OPENSSL_VERSION_NUMBER >= 0x1010000fL
   // for SSL initialization
   SSL_load_error_strings();
   SSL_library_init();
   // Need this to "decrypt" p12 files.
   OpenSSL_add_all_algorithms();
#endif // OPENSSL_101_API
```
do SSL initialization when version >= 1.1, this makes me confused.

I will do a build test with 1.0.2 and 1.1.

**Comment by neheb** [comment]
Oh no no.

0x1010000fL = 1.1.0
0x1002000fL  1.0.2

**Comment by kuoruan** [comment]
Hi @neheb, I tried build with OpenSSL 1.0.2g and OpenSSL 1.1h, both passed and works well on my ramips device.

```
CONFIG_ARIA2_OPENSSL=y
# CONFIG_ARIA2_GNUTLS is not set
# CONFIG_ARIA2_NOSSL is not set
CONFIG_ARIA2_LIBXML2=y
# CONFIG_ARIA2_EXPAT is not set
# CONFIG_ARIA2_NOXML is not set
CONFIG_ARIA2_BITTORRENT=y
CONFIG_ARIA2_METALINK=y
CONFIG_ARIA2_SFTP=y
CONFIG_ARIA2_ASYNC_DNS=y
CONFIG_ARIA2_COOKIE=y
CONFIG_ARIA2_WEBSOCKET=y
```
OpenSSL 1.1 from https://github.com/cotequeiroz/openwrt/tree/openssl-1.1/package/libs/openssl.

**Comment by neheb** [comment]
Try disabling deprecated APIs.

**Comment by neheb** [comment]
Read my comment above. 101 API is 1.1 API.

**Comment by neheb** [comment]
Wait a minute. I’m confusing myself. Looking at define again, it might be doing 1 >= 0x1010000L. I’ll look into this tomorrow.

**Comment by hnyman** [comment]
> Wait a minute. I’m confusing myself. ... I’ll look into this tomorrow.

Are you still confused? ;-)
or is this ok to merge?

**Comment by neheb** [comment]
This change is absolutely correct (tested with both 1.1 and 1.0.2. Why it is correct I have no idea.
