### PR TITLE
postfix: Fix compile with glibc 2.34

### PR DESCRIPTION
**Pull request by hauke**
Maintainer: @Shulyaka 
Compile tested: archs (glibc)
Run tested: none

Description:

This adds a patch from Open embedded to fix compilation with glibc 2.34.
This patch was taken from here:
https://github.com/openembedded/meta-openembedded/blob/master/meta-networking/recipes-daemons/postfix/files/0007-correct-signature-of-closefrom-API.patch

It fixes the following build problem:
/builder/shared-workdir/build/sdk/staging_dir/toolchain-arc_arc700_gcc-11.2.0_glibc/include/unistd.h:366:13: error: conflicting types for 'closefrom'; have 'void(int)'
  366 | extern void closefrom (int __lowfd) __THROW;
      |             ^~~~~~~~~
In file included from attr_clnt.c:87:
./sys_defs.h:1511:12: note: previous declaration of 'closefrom' with type 'int(int)'
 1511 | extern int closefrom(int);
      |            ^~~~~~~~~
make: *** [Makefile:192: attr_clnt.o] Error 1

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Review by Shulyaka — APPROVED** [review]
I think it should not break other libc implementations.
Thank you!
