### PR TITLE
netdata: update to the latest version

### PR DESCRIPTION
**Pull request by tiagogaspar8**
Maintainer: Josef Schlehofer <pepe.schlehofer@gmail.com>, Daniel Engberg <daniel.engberg.lists@pyret.net>
Compile tested: x86 Fedora
Run tested: Ax3600

Description:

Update netdata to the latest version.

This has an issue where the logs aren't logged to the syslog, but the access logs can log to the syslog... If anyone has any idea why this might be happening let me know.

### CODE REVIEW

**Comment by BKPepe** [comment]
CI is failing, but I wonder. Could you compare the size between the old version and the latest one? I believe the latest one is so huge.

**Comment by diizzyy** [comment]
Yeah, there's going to be quite a difference in size

**Comment by BKPepe** [comment]
ping @tiagogaspar8 otherwise I will close this.

**Comment by tiagogaspar8** [comment]
I'm sorry I've been absent, I will see about the reported questions this week, please bear with me.
Thanks.

**Comment by tiagogaspar8** [comment]
Hi everyone,

Thanks for your patience.

Comparing ipkg sizes:
- current: ~7.7MB
- new: ~12.8MB

Regarding the build failures I need to take a look, I haven't had the chance.
Regarding the syslog I need to test with a newer version, though I doubt it will do any difference.

Thanks.

**Comment by tiagogaspar8** [comment]
I was trying to build with version 1.44.1 and I'm getting this:
```
make[5]: Entering directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
aarch64-openwrt-linux-musl-gcc -DHAVE_CONFIG_H -I.   -DVARLIB_DIR="\"/var/lib/netdata\"" 	-DCACHE_DIR="\"/var/cache/netdata\"" 	-DCONFIG_DIR="\"/etc/netdata\"" 	-DLIBCONFIG_DIR="\"/usr/lib/netdata/conf.d\"" 	-DLOG_DIR="\"/var/log/netdata\"" 	-DPLUGINS_DIR="\"/usr/lib/netdata/plugins.d\"" 	-DRUN_DIR="\"/var/run/netdata\"" 	-DWEB_DIR="\"/usr/share/netdata/web\""    -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include/uuid           -pipe -mcpu=cortex-a53 -fno-caller-saves -fno-plt -fhonour-copts -fmacro-prefix-map=/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1=netdata-v1.44.1 -ffunction-sections -fdata-sections -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -O3  -fexceptions         -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include -I/mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/include/uuid                         -I /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1/libnetdata/libjudy/src          -fstack-clash-protection -mbranch-protection=standard -c -o aclk/aclk_util.o aclk/aclk_util.c
aclk/aclk_util.c: In function 'base64_encode_helper':
aclk/aclk_util.c:466:5: error: unknown type name 'EVP_ENCODE_CTX'
  466 |     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
      |     ^~~~~~~~~~~~~~
aclk/aclk_util.c:466:27: warning: implicit declaration of function 'EVP_ENCODE_CTX_new' [-Wimplicit-function-declaration]
  466 |     EVP_ENCODE_CTX *ctx = EVP_ENCODE_CTX_new();
      |                           ^~~~~~~~~~~~~~~~~~
aclk/aclk_util.c:466:27: warning: initialization of 'int *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
aclk/aclk_util.c:467:5: warning: implicit declaration of function 'EVP_EncodeInit' [-Wimplicit-function-declaration]
  467 |     EVP_EncodeInit(ctx);
      |     ^~~~~~~~~~~~~~
aclk/aclk_util.c:468:5: warning: implicit declaration of function 'EVP_EncodeUpdate' [-Wimplicit-function-declaration]
  468 |     EVP_EncodeUpdate(ctx, str, outl, in, in_len);
      |     ^~~~~~~~~~~~~~~~
aclk/aclk_util.c:470:5: warning: implicit declaration of function 'EVP_EncodeFinal' [-Wimplicit-function-declaration]
  470 |     EVP_EncodeFinal(ctx, str, &len);
      |     ^~~~~~~~~~~~~~~
aclk/aclk_util.c:482:5: warning: implicit declaration of function 'EVP_ENCODE_CTX_free' [-Wimplicit-function-declaration]
  482 |     EVP_ENCODE_CTX_free(ctx);
      |     ^~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:8372: aclk/aclk_util.o] Error 1
make[5]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[4]: *** [Makefile:10843: all-recursive] Error 1
make[4]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[3]: *** [Makefile:5092: all] Error 2
make[3]: Leaving directory '/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1'
make[2]: *** [Makefile:109: /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-v1.44.1/.built] Error 2
make[2]: Leaving directory '/mnt/openwrt/ss_mod/feeds/packages/admin/netdata'
time: package/feeds/packages/netdata/compile#12.06#3.41#15.39
    ERROR: package/feeds/packages/netdata failed to build.
```
Any suggestions?

**Comment by tiagogaspar8** [comment]
Adding this here for reference:
https://forum.openwrt.org/t/compiling-error/193090/5

If anyone has a suggestion on how to fix this let me know.

**Comment by tiagogaspar8** [comment]
Hi @BKPepe and @diizzyy,
I have some updates on this PR.

I was able to compile successfully netdata on the version 1.47.5 without ACLK.
ACLK is netdata's sw piece that connects with the cloud to sync dashboard info.

This all sounds great, but netdata 2.0.0 was just released, and it is now mandatory to have ACLK, so now it won't build.

The error I get is this:
```
[121/440] cd /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0 && /mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/bin/protoc-28.3.0 -I/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas --cpp_out=/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas/proto/aclk/v1/lib.proto
FAILED: src/aclk/aclk-schemas/proto/aclk/v1/lib.pb.cc src/aclk/aclk-schemas/proto/aclk/v1/lib.pb.h /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas/proto/aclk/v1/lib.pb.cc /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas/proto/aclk/v1/lib.pb.h 
cd /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0 && /mnt/openwrt/ss_mod/staging_dir/target-aarch64_cortex-a53_musl/usr/bin/protoc-28.3.0 -I/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas --cpp_out=/mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas /mnt/openwrt/ss_mod/build_dir/target-aarch64_cortex-a53_musl/netdata-2.0.0/src/aclk/aclk-schemas/proto/aclk/v1/lib.proto
qemu-aarch64-static: Could not open '/lib/ld-musl-aarch64.so.1': No such file or directory
```
And I think I narrowed it down to this function:
https://github.com/netdata/netdata/blob/v2.0.0/packaging/cmake/Modules/NetdataProtobuf.cmake#L174
this is where netdata calls protobuf to compile the aclk schemas, and it doesn't seem to be linking the libraries correctly.

If you can provide any help here it would be much appreciated, I need guidance on where this might go since I've now hit a roadblock that I won't move past without the help of someone who knows how to code.

Thanks!

**Comment by GeorgeSapkin** [comment]
@tiagogaspar8 any plans to pick this up again?

**Comment by tiagogaspar8** [comment]
Hi @GeorgeSapkin,
I think this is as far as I was able to go, between increasing dependencies, outdated protobuf, and other stuff, I think I was over my head on this.
If you want to pick this up feel free to take what I've done, and I'll be available ( not sure when) to contribute to update the makefile and add more compatible OpenWRT features to netdata, like splitting it in smaller packages etc.
Thanks!

**Comment by xuanranran** [comment]
There are already packages for protobuf 29.5.0. Are there any plans to restart it?

**Comment by tiagogaspar8** [comment]
Hi @xuanranran,

As I said above, I won't be able to do it as the complie errors are getting to a point where I cannot fix them.
If you want to pick up and continue my work you're ok to do so.
I can try to get it to compile it, but at the moment I'm focused on the ripe-atlas package and I'm working on it.

Thanks.

File: admin/netdata/patches/002-support-handling-of-abseil-independently-of-protobuf.patch [hunk 1]
```diff
@@ -0,0 +1,181 @@
...
++function(netdata_detect_abseil _components)
++        set(_components_found "${ENABLE_BUNDLED_ABSEIL}")
++        set(_cflags_other "${NETDATA_ABSEIL_CFLAGS_OTHER}")
++        set(_include_dirs "${NETDATA_ABSEIL_INCLUDE_DIRS}")
++        set(_libs "${NETDATA_ABSEIL_LIBS}")
++        set(_bundled "${BUNDLED_ABSEIL}")
++
++        if(NOT BUNDLED_ABSEIL)
++                if(NOT ENABLE_BUNDLED_ABSEIL)
++                        foreach(_c LISTS _components)
```
Comment (openwrt-ai) [inline admin/netdata/patches/002-support-handling-of-abseil-independently-of-protobuf.patch:71]: These `foreach()` calls are missing the `IN` keyword, so they never iterate over the intended list/items. Without `IN`, CMake reads `foreach(_c LISTS _components)` as "iterate `_c` over the literal values `LISTS` and `_components`", so `_component_name` becomes `absl_LISTS` / `absl__components` and the system-Abseil detection can never match. The correct form is:

```
foreach(_c IN LISTS _components)
```

The same defect appears at the second `foreach(_c LISTS _components)` (line 97) and at `foreach(_var ITEMS _cflags_other _include_dirs _libs)` (line 120), which needs `foreach(_var IN ITEMS _cflags_other _include_dirs _libs)`.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
## Commit checks

- The single commit `909f61e` ("netdata: update to the latest version") is consistent with its changes (version bump 1.33.1 → 2.1.0, autotools→CMake migration, dependency additions, and patch refresh). One hygiene nit: the `Co-authored-by: Aditya Nugraha` trailer has no `<email>`, so it is malformed and GitHub cannot attribute the co-author — use `Co-authored-by: Name <email>`.

Reviewed 1 new commit; one inline issue noted (CMake `foreach ... IN` in the new Abseil patch). CI has no recorded check runs on the head commit, so nothing to walk there.

---
_Generated by [Claude Code](https://claude.ai/code)_
