### PR TITLE
dockerd: initialize network config once

### LINKED ISSUE #29962: dockerd: boot() calls uciadd() triggering reload_config which causes fw4 "redefinition of symbol 'docker_devices'" error on every boot
### Package Name

dockerd

### Maintainer

Gerard Ryan (G.M.Ryan) <gerard@ryanr.co.uk>

### OpenWrt Version

25.12.4

### OpenWrt Target/Subtarget

rockchip/armv8

### Steps to Reproduce

1. Install dockerd and configure iptables=0 in /etc/config/dockerd                                                                                                                                            
2. Ensure a firewall zone named docker already exists in /etc/config/firewall (created by uciadd() on first install)                                                                                          
3. Reboot OR run /etc/init.d/firewall stop && /etc/init.d/firewall start                                                                                                                                      
4. Observe error: Error: redefinition of symbol 'docker_devices' during fw4 start 

### Actual Behaviour

After power loss or manual restart, fw4 fails to apply rules due to docker_devices symbol redefinition. The firewall remains active with no instances. Running /etc/init.d/dockerd boot triggers uciadd() → reload_config → fw4 tries to redefine already-existing nftables symbol, which fails. Removing and reinstalling dockerd packages temporarily "fixes" it because pre/post scripts recreate the firewall zone, but the issue returns after the next reboot.

Root cause: boot() in /etc/init.d/dockerd unconditionally calls uciadd(), which calls reload_config. Since dockerd starts after fw4 (S99 vs S19), fw4 already has its rules loaded. reload_config triggers fw4 to re-apply its ruleset incrementally, but fw4 uses nft -f (not nft flush ruleset first), causing redefinition of symbol 'docker_devices' because docker_devices is already defined by the previously applied ruleset.

When iptables=0, the iptables management is skipped, but uciadd() still runs unconditionally in boot(), still calling reload_config, still triggering the fw4 
reload, causing the same error.                                                                                                                                                                               
                                                                                                                                                                                                                   
Workaround: Commenting out uciadd in boot() and cleaning up duplicate firewall zones resolves the issue.                                          

Expected Behaviour:

boot() should either:
- Not call uciadd() if the docker firewall zone already exists, OR
- Check iptables config option before calling uciadd(), OR
- Move uciadd() to start_service() and only call it on first install, not on every boot

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by Cryptoteep**
## Package Details

**Maintainer:** @G-M0N3Y-2503

**Description:**
Stop invoking `uciadd` from the dockerd boot hook. Package installation already creates the network and firewall configuration; repeating it after fw4 has loaded triggers `reload_config` and can fail with a `docker_devices` symbol redefinition. The package release is bumped and a functional regression test asserts that boot starts dockerd without mutating UCI.

Closes #29962

---

## Run Testing Details

- **OpenWrt Version:** 25.12.4 (reported reproduction)
- **OpenWrt Target/Subtarget:** rockchip/armv8
- **OpenWrt Device:** not specified in the issue
- **Local:** `DOCKERD_INIT_SCRIPT=utils/dockerd/files/dockerd.init sh utils/dockerd/test.sh` passes under WSL/BusyBox-compatible shell

---

## Formalities

- [x] I have reviewed the CONTRIBUTING.md file for detailed contributing guidelines.

### If your PR contains a patch:

Not applicable; this changes the package init script directly and does not add or refresh an upstream source patch.

### CODE REVIEW

**Comment by G-M0N3Y-2503** [comment]
I'm not sure the fix is as simple as removing from boot https://github.com/openwrt/packages/pull/12897

File: utils/dockerd/files/dockerd.init [hunk 1]
```diff
@@ -40,7 +40,6 @@ find_network_device() {
 }
 
 boot() {
-	uciadd
 	rc_procd start_service
```
Comment (openwrt-ai) [inline utils/dockerd/files/dockerd.init:43]: Removing `uciadd` from `boot()` looks like it regresses the case where dockerd is baked into the firmware image rather than installed at runtime.

`Package/dockerd/postinst` runs `uciadd` only inside the `[ -n "$IPKG_INSTROOT" ] || { ... }` guard, so it is skipped during image build (ImageBuilder/buildroot), where `IPKG_INSTROOT` is set. The build system's `default_postinst` re-runs only `/etc/uci-defaults/` scripts on first boot, not the package's `postinst-pkg` body, so the guarded `uciadd` never runs on such systems. `boot()` was therefore the only path that created the `docker` network interface, `docker0` bridge device and `docker` firewall zone on first boot for image-preinstalled dockerd; it was idempotent for runtime installs because `uciadd` gates every mutation behind `if ! uci_quiet get ...`.

With this change, a device that ships dockerd in its image would boot without the docker network/firewall UCI config ever being created. This lines up with the maintainer's doubt in the PR thread ("I'm not sure the fix is as simple as removing from boot").

If the goal is only to avoid the `reload_config` at boot (the `docker_devices` redefinition), consider addressing that specific reload/idempotency issue instead of dropping config creation entirely — e.g. keep the config-creation on first boot but skip `reload_config`, or move the one-time creation into an `/etc/uci-defaults/` script so it is deferred to first boot for image-preinstalled systems. Could you confirm how image-preinstalled installs are expected to get the docker network/firewall config after this change?

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit. The commit message matches the change. One inline comment on a possible functional regression for image-preinstalled installs.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by brada4** [comment]
@G-M0N3Y-2503 it is on you to unfXck the firewall now,

**Review by brada4 — APPROVED** [review]
This addresses breaking the firewall on 3rd reboot correctly.

**Comment by brada4** [comment]
@BKPepe please help either reverting rogue commit disabling (!!!) firewall or at least applying minimal fixup. Thanks. Commit title IS the description.

File: utils/dockerd/files/dockerd.init (hunk 1 above)
Comment (G-M0N3Y-2503) [reply utils/dockerd/files/dockerd.init:43]: I think the idempotency is the issue, because we are dealing with the firewall the reload was to ensure the firewall is in the expected shape before dockerd starts if I recall correctly.
I'm not sure why this is an issue all of a sudden, or why reloading an unchanged firewall breaks anything.

**Review by openwrt-ai — COMMENTED** [review]
Reviewed the update since my last review. The force-push was a rebase of the branch onto a newer `master`: the `dockerd` commit is unchanged (identical message and diff — no `utils/dockerd/` files differ between the previously reviewed commit and the current head `fcb7121`), and the remaining files in the range are unrelated changes already merged to `master`.

No new issues found in this update. My earlier inline note on `utils/dockerd/files/dockerd.init` (potential regression for image-preinstalled/ImageBuilder installs, where `boot()` was the only path creating the docker network/firewall UCI config) still applies and appears to be under discussion in the thread.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Cryptoteep** [comment]
Updated the approach based on the image-preinstalled concern. boot() still calls uciadd, preserving first-boot UCI creation. uciadd now tracks whether it actually created an interface/device/zone or added the zone network, and calls reload_config only after a real change. Existing configs therefore skip the redundant fw4 reload, while image-built installs retain initialization. The commit now also has the required explanatory body; the functional regression test covers both invariants.

**Comment by brada4** [comment]
Automated review suggested to use one time uci-defaults script, not the general everyday script to add ifaces.

**Review by brada4 — CHANGES_REQUESTED** [review]
67

File: utils/dockerd/files/dockerd.init [hunk 2]
```diff
@@ -92,16 +95,18 @@ uciadd() {
...
 		uci_quiet set firewall.@zone[-1].name="${zone}"
 		uci_quiet commit firewall
+		changed=1
 	fi
 
 	# Add interface to firewall zone
-	if uci_quiet get firewall.${zone}; then
-		uci_quiet del_list firewall.${zone}.network="${iface}"
+	if uci_quiet get firewall.${zone} \
+		&& ! uci_quiet get firewall.${zone}.network | tr ' ' '\n' | grep -Fxq "${iface}"; then
```
Comment (openwrt-ai) [inline utils/dockerd/files/dockerd.init]: This membership check never sees the list, so the reload it is meant to gate still fires on every boot. `uci_quiet` sends its stdout to `/dev/null` (`uci -q "${@}" >/dev/null`), so `uci_quiet get firewall.${zone}.network | tr ... | grep -Fxq "${iface}"` reads an empty stream, `grep` never matches, and the `!` makes the second condition always true. On a normal reboot the zone already exists, so this branch runs `add_list` + `commit firewall` every time, sets `changed=1`, and calls `reload_config` — defeating the PR's goal of skipping the reload when nothing changed. It also appends a duplicate `${iface}` to `firewall.${zone}.network` on each boot, since `uci add_list` does not deduplicate (that is why the previous code paired `del_list` with `add_list`).

Use the non-silencing form for the read so its output reaches the pipe:

```suggestion
	if uci_quiet get firewall.${zone} \
		&& ! uci -q get firewall.${zone}.network | tr ' ' '\n' | grep -Fxq "${iface}"; then
```

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
## Commit checks

- Commit `a716496` body line 3 is 234 characters, exceeding the 100-char commit-body limit (already flagged by the formality bot). Wrap the body so each line stays under the limit.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

The force-push amended the single `dockerd` commit: the body was rewrapped (each line now under 100 chars, resolving the earlier FormalityCheck flag) and the only code change is `uci_quiet get firewall.${zone}.network` → `uci -q get firewall.${zone}.network`. This is a correct fix — `uci_quiet` discards stdout, so the previous membership test fed `grep` empty input and the interface was re-added (with a firewall reload) on every boot; `uci -q get` restores stdout to the pipe. The new commit-body paragraph accurately describes the change.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: utils/dockerd/files/dockerd.init (hunk 1 above)
Comment (Cryptoteep) [reply utils/dockerd/files/dockerd.init:43]: The failure mode is described in #29962: on a device where the docker zone already exists, every boot goes `uciadd` → `reload_config` → fw4 reload, and that reload fails with `Error: redefinition of symbol 'docker_devices'`, leaving fw4 running with no instances (reported on 25.12.4 with `iptables=0`). So the reload is not a harmless no-op — it re-runs fw4 against state where dockerd's nftables objects already exist.

This PR keeps the boot-time `uciadd`, so the firewall is still ensured to be in the expected shape before dockerd starts (and image-preinstalled setups still get initialized on first boot). The only change is that `reload_config` is skipped when `uciadd` didn't actually modify UCI — i.e. the everyday reboot path no longer touches fw4 at all.

**Comment by Cryptoteep** [comment]
@brada4 I did consider moving the setup into a one-time `/etc/uci-defaults` script — it is the canonical mechanism and would also cover image builds. But it changes the semantics from "ensure the config each boot" to "create once": initialization was put into `boot()` deliberately (#12897 lineage) so the zone/interface is (re)ensured before dockerd starts. To keep this PR a minimal fix for #29962 I kept the boot-time `uciadd` and made it side-effect-free instead: on a normal reboot it performs no UCI writes and no `reload_config` at all, so nothing gets added or reloaded on the "everyday" path.

If @G-M0N3Y-2503 prefers the uci-defaults route, I'm happy to rework the PR that way.

**Comment by brada4** [comment]
It has to be "create once"

**Comment by Cryptoteep** [comment]
Reworked as requested in 3e4e09a58: docker network/firewall initialization now runs from /etc/uci-defaults/dockerd exactly once, boot() only starts the service, and the duplicate postinst uciadd call is removed. uciadd remains idempotent for manual use. Rebased onto current master; the focused functional test passes.

**Comment by Cryptoteep** [comment]
Wrapped the commit body to satisfy the 100-column formality rule; updated head is 0a05eb83d.

**Comment by Cryptoteep** [comment]
CI log showed the package test was checking /etc/uci-defaults/dockerd after default_postinst had correctly removed the one-time script. Removed that invalid assertion in b27e3c42d; boot/idempotency checks remain. This is a test-only correction; pushed for CI rerun.

File: utils/dockerd/files/dockerd.init [hunk 3]
```diff
@@ -92,16 +94,18 @@ uciadd() {
...
```
Comment (openwrt-ai) [inline utils/dockerd/files/dockerd.init]: The membership check reads from `uci_quiet`, which reintroduces a bug that a prior revision had fixed. `uci_quiet` redirects stdout to `/dev/null` (`uci -q "${@}" >/dev/null`, line 13), so `uci_quiet get firewall.${zone}.network` puts nothing on the pipe: `tr`/`grep` see an empty stream, `grep -Fxq` never matches, and `!` makes the condition always true. On a device where the `docker` zone already exists, this runs `add_list` + `commit firewall` and sets `changed=1` on every `uciadd` invocation, so `reload_config` fires even when nothing changed — defeating this commit's stated goal of reloading only when UCI actually changes (and re-adding a duplicate `${iface}`, since `uci add_list` does not deduplicate). Use the non-silencing read so its output reaches the pipe:

```suggestion
		&& ! uci -q get firewall.${zone}.network | tr ' ' '\n' | grep -Fxq "${iface}"; then
```

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; 1 issue found.

The commit message accurately describes the diff (the `PKG_VERSION:=29.6.1` bump comes from `master` via rebase, not this commit). One inline comment: the firewall membership check was reverted from `uci -q get` back to `uci_quiet get`, reintroducing a bug flagged and fixed in an earlier revision.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Cryptoteep** [comment]
Fixed in 5c080c8: the membership check read from `uci_quiet`, so it always got an empty stream and `reload_config` fired every boot. Switched that read to `uci -q` so its output reaches the pipe. Local test passes.

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

The new commit re-applies the `uci_quiet get firewall.${zone}.network` → `uci -q get firewall.${zone}.network` fix that was flagged as reverted in my previous review. Since `uci_quiet()` redirects stdout to `/dev/null`, using it for the membership check fed `tr`/`grep` an empty stream, so the interface was always re-added and `reload_config` fired on every boot. `uci -q get` restores stdout to the pipe. The commit message accurately describes the change.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: utils/dockerd/test.sh [hunk 4]
```diff
@@ -0,0 +1,21 @@
...
+	echo "dockerd boot() does not start the service" >&2
+	exit 1
+}
+
+if echo "${boot_body}" | grep -qw uciadd; then
+	echo "dockerd boot() must not re-run one-time UCI initialization" >&2
+	exit 1
+fi
+
+grep -q '\[ "${changed}" -eq 0 \] || reload_config' "${init_script}" || {
```
Comment (openwrt-ai) [inline utils/dockerd/test.sh:18]: This asserts an exact source line of the init script rather than any behaviour, so it breaks on a purely cosmetic edit. The pattern has to match [`[ "${changed}" -eq 0 ] || reload_config`](https://github.com/openwrt/packages/blob/78f0d5740f8c2b8942b7887299393539c5ca2bec/utils/dockerd/files/dockerd.init#L108) character for character — renaming `changed`, dropping the braces, or switching to `[ "$changed" = 0 ]` all turn this into a red CI run for a package that still works. The same applies to the two `boot()` greps above: line 8 pins the literal `rc_procd start_service`, which is what makes the now-redundant `boot()` override un-removable, since rc.common's [default `boot()`](https://github.com/openwrt/openwrt/blob/70b3f992b81462f5cc5ba24ca41aaadd0186e1a4/package/base-files/files/etc/rc.common#L30-L32) already resolves to the procd `start()` and dockerd defines no `service_started` hook.

`test.sh` runs inside the runtime-test VM with the package installed, so it can check the actual effect instead: run `/etc/init.d/dockerd uciadd` twice and assert that the second invocation leaves `network`/`firewall` UCI unchanged (e.g. compare `uci show firewall` before and after). That covers the regression this PR fixes without freezing the implementation text. Not blocking — just flagging that as written this test is a copy of the diff rather than a guard on it.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: utils/dockerd/test.sh [hunk 5]
```diff
@@ -0,0 +1,21 @@
+#!/bin/sh
+
+# shellcheck shell=busybox
+
+init_script="${DOCKERD_INIT_SCRIPT:-/etc/init.d/dockerd}"
+boot_body="$(sed -n '/^boot() {$/,/^}$/p' "${init_script}")"
+
+echo "${boot_body}" | grep -q 'rc_procd start_service' || {
```
Comment (openwrt-ai) [inline utils/dockerd/test.sh:8]: nit: quiet mode in `grep` is discouraged in `test.sh` scripts — leaving the matched line in the output means the CI log shows what was actually found when a check fails, instead of only the hand-written error string.

```suggestion
echo "${boot_body}" | grep 'rc_procd start_service' || {
```

Same applies to `grep -qw uciadd` on line 13 and `grep -q` on line 18 (there the `-q` can just be dropped too).

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 2 new commits; no new code issues found.

The force-push since my last review was a pure rebase onto current `master`: both `utils/dockerd/` commits (`31fd05e`, `78f0d57`) are byte-identical in message and diff to the previously reviewed `b27e3c42`/`5c080c87`, and `git diff 5c080c8..78f0d57 -- utils/dockerd/` is empty. The `uci -q get firewall.${zone}.network` fix I confirmed last time is still in place, and the uci-defaults rework matches what the thread asked for — with the ordering in [`default_postinst`](https://github.com/openwrt/openwrt/blob/70b3f992b81462f5cc5ba24ca41aaadd0186e1a4/package/base-files/files/lib/functions.sh#L384-L398) running `/etc/uci-defaults/` before `postinst-pkg`, the config is created before `postinst` starts the service, so dropping `uciadd` from `postinst` is safe.

Two optional comments on the new `test.sh`; neither blocks a merge.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by G-M0N3Y-2503** [comment]
Reading through the [Docker firewall documentation](https://docs.docker.com/engine/network/packet-filtering-firewalls/) it looks like it has change a fair bit since last I had the pleasure. 

I also couldn't find anywhere where we found the root cause of this issue in the first place, just the steps to reproduce.

So it's hard to say weather this fix is correct or a good fit that will work generally in many different environments.
I'm most concerned weather stopping the reload will let `docker` create rules to open everything up like it use to.

We'd need to know what `docker` is doing these days with the rules it creates, since we are using `iptables` (via the `nft` adapter) what it supports, what and, how `fw4` allows custom rules then how we can help everything play nicely.

**Comment by G-M0N3Y-2503** [comment]
https://github.com/Cryptoteep/packages/blob/78f0d5740f8c2b8942b7887299393539c5ca2bec/utils/dockerd/files/etc/config/dockerd#L31

Actually I don't think fw4 ever worked, I'm recalling now that I use fw3 for all my tests. So I think this is a much bigger rework.

For this kind of change (not a rework) we'd need to ensure this works with fw3 still as we don't want to break the actually supported configuration for a potentially partially working hybrid configuration.

**Comment by Cryptoteep** [comment]
Added the missing Signed-off-by trailer to the firewall membership fix and force-pushed 38dae1b49. The focused dockerd package test passes locally; no code changed in this update.

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

---
_Generated by [Claude Code](https://claude.ai/code)_

File: utils/dockerd/files/dockerd.init (hunk 2 above)
Comment (openwrt-ai) [reply utils/dockerd/files/dockerd.init]: fixed, thanks

---
_Generated by [Claude Code](https://claude.ai/code)_

File: utils/dockerd/files/dockerd.init (hunk 3 above)
Comment (openwrt-ai) [reply utils/dockerd/files/dockerd.init]: fixed, thanks

---
_Generated by [Claude Code](https://claude.ai/code)_
