### PR TITLE
ripe-atlas: update to 5130

### LINKED ISSUE #30083: ripe-atlas: linking error
### Package Name

ripe-atlas

### Maintainer

@commodo

### OpenWrt Version

SNAPSHOT

### OpenWrt Target/Subtarget

x86/64

### Steps to Reproduce

1. Compile with gcc 16.1.0
2. Observe the linking error

Also I need the following patch to concatenated comments, unless compilation errors : 
```
--- a/probe-busybox/eperd/evtdig.c
+++ b/probe-busybox/eperd/evtdig.c
@@ -23,7 +23,8 @@
 //config:       default n
 //config:       depends on EVTDIG
 //config:       help
-//config:        extra debug info. Also may cause segfault or/and memory leak. Add at your own risk.
+//config:        extra debug info. Also may cause segfault or/and
+//config:        memory leak. Add at your own risk.
 
 //applet:IF_EVTDIG(APPLET(evtdig, BB_DIR_ROOT, BB_SUID_DROP))
 
``` 

### Actual Behaviour

Getting the following linking error : 
```
  GEN     archival/libarchive/Kbuild
  GEN     libpwdgrp/Kbuild
  GEN     eperd/Kbuild
  GEN     eperd/Config.in
In file included from scripts/kconfig/zconf.tab.c:2168:
scripts/kconfig/confdata.c: In function 'conf_write':
scripts/kconfig/confdata.c:353:35: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  353 |                 } else if ((slash = strrchr(name, '/'))) {
      |                                   ^
scripts/kconfig/conf -s Config.in
#
# using defaults found in .config
#
/home/nameless/works/openwrt/staging_dir/toolchain-x86_64_gcc-16.1.1_glibc/bin/x86_64-openwrt-linux-gnu-ld.bfd: -f may not be used without -shared
make[5]: *** [scripts/Makefile.build:264: applets/built-in.o] Error 1
make[4]: *** [Makefile:372: applets_dir] Error 2
make[3]: *** [Makefile:469: all-recursive] Error 1
make[3]: Leaving directory '/home/nameless/works/openwrt/build_dir/target-x86_64_glibc_nameless/ripe-atlas-software-probe-5120'
make[2]: *** [Makefile:209: /home/nameless/works/openwrt/build_dir/target-x86_64_glibc_nameless/ripe-atlas-software-probe-5120/.built] Error 2
```

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by commodo**
## 📦 Package Details

**Maintainer:** @tiagogaspar8
<sub>(You can find this by checking the history of the package `Makefile`.)</sub>

**Description:**

5130 removed --with-probe-type; generic is the default now, selected by not passing --enable-hwprobe. Drop 001-uname.patch, upstream took the `uname -n` change in 5120.

Also set LD back to busybox's "$(CC) -nostdlib": OpenWrt's MAKE_FLAGS force the raw ld.bfd, which rejects the compiler-driver flags in OpenWrt's LDFLAGS (-fuse-ld=, -specs=, -flto=) with "-f may not be used without -shared".

Fixes: https://github.com/openwrt/packages/issues/30083

Related to https://github.com/openwrt/packages/pull/30067

---

## 🧪 Run Testing Details

- **OpenWrt Version:**
- **OpenWrt Target/Subtarget:**
- **OpenWrt Device:**

---

## ✅ Formalities

- [ ] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### CODE REVIEW

File: net/ripe-atlas/Makefile [hunk 1]
```diff
@@ -23,6 +23,9 @@ PKG_INSTALL:=1
 
 include $(INCLUDE_DIR)/package.mk
 
+# Restore busybox's compiler-driver LD; OpenWrt overrides it with raw ld.bfd.
+MAKE_FLAGS += LD="$(TARGET_CC) -nostdlib"
```
Comment (openwrt-ai) [inline net/ripe-atlas/Makefile:27]: This hunk and the `001-uname.patch` removal are byte-identical to the ones in your still-open [#30067](https://github.com/openwrt/packages/pull/30067), which bumps to 5120 and additionally adds `files/ripe-atlas.defaults` (the probe-key/uci migration from `atlas-sw-probe`). Whichever lands second will need a rebase, and the migration script is not carried over here — is #30067 meant to be closed in favour of this, or rebased on top of it?

---
_Generated by [Claude Code](https://claude.ai/code)_

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit.

---
_Generated by [Claude Code](https://claude.ai/code)_
