### ISSUE TITLE
ripe-atlas: linking error

### ISSUE THREAD

**Issue by vortexilation** [openwrt/packages#30083]
### Package Name

ripe-atlas

### Maintainer

@commodo

### OpenWrt Version

SNAPSHOT

### OpenWrt Target/Subtarget

x86/64

### Steps to Reproduce

1. Compile with gcc 16.1.0
2. Observe the linking error

Also I need the following patch to concatenated comments, unless compilation errors : 
```
--- a/probe-busybox/eperd/evtdig.c
+++ b/probe-busybox/eperd/evtdig.c
@@ -23,7 +23,8 @@
 //config:       default n
 //config:       depends on EVTDIG
 //config:       help
-//config:        extra debug info. Also may cause segfault or/and memory leak. Add at your own risk.
+//config:        extra debug info. Also may cause segfault or/and
+//config:        memory leak. Add at your own risk.
 
 //applet:IF_EVTDIG(APPLET(evtdig, BB_DIR_ROOT, BB_SUID_DROP))
 
``` 

### Actual Behaviour

Getting the following linking error : 
```
  GEN     archival/libarchive/Kbuild
  GEN     libpwdgrp/Kbuild
  GEN     eperd/Kbuild
  GEN     eperd/Config.in
In file included from scripts/kconfig/zconf.tab.c:2168:
scripts/kconfig/confdata.c: In function 'conf_write':
scripts/kconfig/confdata.c:353:35: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  353 |                 } else if ((slash = strrchr(name, '/'))) {
      |                                   ^
scripts/kconfig/conf -s Config.in
#
# using defaults found in .config
#
/home/nameless/works/openwrt/staging_dir/toolchain-x86_64_gcc-16.1.1_glibc/bin/x86_64-openwrt-linux-gnu-ld.bfd: -f may not be used without -shared
make[5]: *** [scripts/Makefile.build:264: applets/built-in.o] Error 1
make[4]: *** [Makefile:372: applets_dir] Error 2
make[3]: *** [Makefile:469: all-recursive] Error 1
make[3]: Leaving directory '/home/nameless/works/openwrt/build_dir/target-x86_64_glibc_nameless/ripe-atlas-software-probe-5120'
make[2]: *** [Makefile:209: /home/nameless/works/openwrt/build_dir/target-x86_64_glibc_nameless/ripe-atlas-software-probe-5120/.built] Error 2
```

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by commodo** [comment]
Will check it out

**Comment by vortexilation** [comment]
@commodo 

Proposed fixes from claude : 
```
--- a/probe-busybox/scripts/Makefile.build
+++ b/probe-busybox/scripts/Makefile.build
@@ -257,7 +257,7 @@
 # If the list of objects to link is empty, just create an empty built-in.o
 # -nostdlib is added to make "make LD=gcc ..." work (some people use that)
 cmd_link_o_target = $(if $(strip $(obj-y)),\
-		$(LD) -nostdlib $(ld_flags) -r -o $@ $(filter $(obj-y), $^),\
+		$(LD) -nostdlib $(filter-out -f%,$(ld_flags)) -r -o $@ $(filter $(obj-y), $^),\
 		rm -f $@; $(AR) rcs $@)
 
 $(builtin-target): $(obj-y) FORCE
```

**Comment by commodo** [comment]
@vortexilation 

See PR: https://github.com/openwrt/packages/pull/30067/changes

I think we can fix this without patching ripe-atlas.

And for the config change, we will not patch it in OpenWrt.
Will push it upstream.

i.e. this
```
-//config:        extra debug info. Also may cause segfault or/and memory leak. Add at your own risk.
+//config:        extra debug info. Also may cause segfault or/and
+//config:        memory leak. Add at your own risk.
```

**Comment by vortexilation** [comment]
@commodo 
Thanks but hmm still getting the same error with your proposed solution.


Here is the proposed and tested fixes by claude : 
```
# The bundled probe-busybox is a kbuild tree that links built-in.o with
# "$(LD) -r" and feeds $(LDFLAGS) straight to it. It expects LD to be the
# compiler driver ("LD = $(CC) -nostdlib"), but TARGET_CONFIGURE_OPTS points
# LD at ld.bfd, which then chokes on -fuse-ld=/-flto=/-fPIC/-specs= with
# "-f may not be used without -shared". Restore busybox's own default.
MAKE_FLAGS += LD="$(TARGET_CC) -nostdlib"
```

**Comment by commodo** [comment]
So, upstream-wise

https://github.com/RIPE-NCC/ripe-atlas-software-probe/issues/150#issuecomment-5160409322

https://github.com/RIPE-NCC/ripe-atlas-software-probe/pull/149

We will do the minimum for now, for RIPE Atlas in OpenWrt and wait for usptream :)

Thanks

**Comment by commodo** [comment]
> [@commodo](https://github.com/commodo) Thanks but hmm still getting the same error with your proposed solution.
> 
> Here is the proposed and tested fixes by claude :
> 
> ```
> # The bundled probe-busybox is a kbuild tree that links built-in.o with
> # "$(LD) -r" and feeds $(LDFLAGS) straight to it. It expects LD to be the
> # compiler driver ("LD = $(CC) -nostdlib"), but TARGET_CONFIGURE_OPTS points
> # LD at ld.bfd, which then chokes on -fuse-ld=/-flto=/-fPIC/-specs= with
> # "-f may not be used without -shared". Restore busybox's own default.
> MAKE_FLAGS += LD="$(TARGET_CC) -nostdlib"
> ```

will check it out

**Comment by vortexilation** [comment]
@commodo 
Nice the long comment got merged, thanks man.
