### PR TITLE
Openvswitch

### PR DESCRIPTION
**Pull request by findlayfeng**
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: 23.05-SNAPSHOT
Run tested: 23.05-SNAPSHOT

Description:
fix openvswitch build parameters 
rewrote openvswitch init script 
update openvswitch

### CODE REVIEW

**Comment by trippleflux** [comment]
@findlayfeng 
Any ideas on how to fixes this : 
```
if cmp -s version.py.tmp python/ovs/version.py; then touch python/ovs/version.py; rm version.py.tmp; else mv version.py.tmp python/ovs/version.py; fi
PYTHONPATH=$PYTHONPATH":"./python python3.11 ./build-aux/soexpand.py -I. < utilities/ovs-lib.in | \
  python3.11 ./build-aux/dpdkstrip.py --nodpdk | \
  sed \
    -e 's,[@]PKIDIR[@],/var/lib/openvswitch/pki,g' \
    -e 's,[@]LOGDIR[@],/var/log/openvswitch,g' \
    -e 's,[@]DBDIR[@],/etc/openvswitch,g' \
    -e 's,[@]PYTHON3[@],python3.11,g' \
    -e 's,[@]RUNDIR[@],/var/run/openvswitch,g' \
    -e 's,[@]VERSION[@],2.17.7,g' \
    -e 's,[@]localstatedir[@],/var,g' \
    -e 's,[@]pkgdatadir[@],/usr/share/openvswitch,g' \
    -e 's,[@]sysconfdir[@],/etc,g' \
    -e 's,[@]bindir[@],/usr/bin,g' \
    -e 's,[@]sbindir[@],/usr/sbin,g' \
    -e 's,[@]abs_builddir[@],/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7,g' \
    -e 's,[@]abs_top_srcdir[@],/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7,g' \
  > utilities/ovs-lib.tmp
Traceback (most recent call last):
  File "/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7/./build-aux/soexpand.py", line 17, in <module>
    from build import soutil
ImportError: cannot import name 'soutil' from 'build' (/home/user/works/openwrt/staging_dir/hostpkg/lib/python3.11/site-packages/build/__init__.py)
```

**Comment by findlayfeng** [comment]
@trippleflux 
Hi
I am using translation tool.
I'm working on archlinux, and openvswitch-2.17.0 did have problems during the build process, the problem was in the process of building the documentation for ovs, the syntax of the 2.17.0 documentation build script may be a bit outdated (yes, this Part of the build uses the host's toolchain) I chose to patch the makefile([d786cf1](https://github.com/openwrt/packages/pull/21650/commits/d786cf10fb7ebe7f527ccb2e65d2a5b9e6fe3306)), skipped the build of the documentation, and ignored it when packaging anyway.

> @findlayfeng Any ideas on how to fixes this :
> 
> ```
> if cmp -s version.py.tmp python/ovs/version.py; then touch python/ovs/version.py; rm version.py.tmp; else mv version.py.tmp python/ovs/version.py; fi
> PYTHONPATH=$PYTHONPATH":"./python python3.11 ./build-aux/soexpand.py -I. < utilities/ovs-lib.in | \
>   python3.11 ./build-aux/dpdkstrip.py --nodpdk | \
>   sed \
>     -e 's,[@]PKIDIR[@],/var/lib/openvswitch/pki,g' \
>     -e 's,[@]LOGDIR[@],/var/log/openvswitch,g' \
>     -e 's,[@]DBDIR[@],/etc/openvswitch,g' \
>     -e 's,[@]PYTHON3[@],python3.11,g' \
>     -e 's,[@]RUNDIR[@],/var/run/openvswitch,g' \
>     -e 's,[@]VERSION[@],2.17.7,g' \
>     -e 's,[@]localstatedir[@],/var,g' \
>     -e 's,[@]pkgdatadir[@],/usr/share/openvswitch,g' \
>     -e 's,[@]sysconfdir[@],/etc,g' \
>     -e 's,[@]bindir[@],/usr/bin,g' \
>     -e 's,[@]sbindir[@],/usr/sbin,g' \
>     -e 's,[@]abs_builddir[@],/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7,g' \
>     -e 's,[@]abs_top_srcdir[@],/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7,g' \
>   > utilities/ovs-lib.tmp
> Traceback (most recent call last):
>   File "/home/user/works/openwrt/build_dir/target-x86_64_glibc_user/linux-x86_64/openvswitch-2.17.7/./build-aux/soexpand.py", line 17, in <module>
>     from build import soutil
> ImportError: cannot import name 'soutil' from 'build' (/home/user/works/openwrt/staging_dir/hostpkg/lib/python3.11/site-packages/build/__init__.py)
> ```
> 
> The differences is I am trying to compile latest 2.17.* branch :
> 
> ```
> ovs_version:=2.17.7
> ```
> 
> The openvswitch-2.17.0 also failed to compile on my build host, debian unstable, python 3.10.12.

I don't know if the error reported when you build version 2.17.0 is consistent with this paragraph. The error here is because a python package is missing in the build dependencies, which causes the ovs build script to not work properly. Generally, in this case, check Does the build dependency meet the requirements of ovs?

**Comment by trippleflux** [comment]
Seems compiled fine now, thanks @findlayfeng .

**Comment by BKPepe** [comment]
@yousong Can you look into this?
