### PR TITLE
xtables-addons: fix build with newer kernels

### PR DESCRIPTION
**Pull request by dthnguyen**
## 📦 Package Details

**Maintainer:** Jo-Philipp Wich <jo@mein.io>

**Description:**

This PR fixes xtables-addons build failures with newer Linux kernels.

Changes included:

1. Replace deprecated `EXTRA_CFLAGS` usage with `ccflags-y` in extension
   Kbuild files so local include paths and compiler flags are correctly
   propagated by modern kbuild.

2. Update the `pknock` extension to support newer timer APIs by using
   the appropriate timer helpers on newer kernels while maintaining
   compatibility with older kernels.

These fixes resolve build failures observed when compiling xtables-addons
against Linux 6.18.

Affected build failures include:

```text
ACCOUNT/xt_ACCOUNT.c: fatal error: compat_xtables.h: No such file or directory

LUA/controller.h: fatal error: stdlib.h: No such file or directory

pknock/xt_pknock.c: error: implicit declaration of function 'del_timer'
pknock/xt_pknock.c: error: implicit declaration of function 'from_timer'
```

---

## 🧪 Run Testing Details

- **OpenWrt Version:** master
- **OpenWrt Target/Subtarget:** mediatek/filogic
- **OpenWrt Device:** ZBT Z8803BE

Build-tested with:

- Linux 6.18.x
- aarch64 (MediaTek Filogic)

---

## ✅ Formalities

- [x] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### If your PR contains a patch:

- [x] It can be applied using `git am`
- [ ] It has been refreshed to avoid offsets, fuzzes, etc., using

  ```bash
  make package/xtables-addons/refresh V=s
  ```

- [x] It is structured in a way that it is potentially upstreamable

<sub>(e.g., subject line, commit description, etc.)</sub>

<sub>We must try to upstream patches to reduce maintenance burden.</sub>

### CODE REVIEW

**Comment by LGA1150** [comment]
Your code base is outdated. It's already fixed in #28167.

**Comment by dthnguyen** [comment]
ok, thanks @LGA1150 , i confirmed the build works fine with v3.30
