### PR TITLE
sing-box: bump to 1.13.21

### LINKED ISSUE #30423: sing-box-full fails to build with Go 1.27: undefined: json.SkipFunc, json.DiscardUnknownMembers
### Package Name

sing-box

### Maintainer

Van Waholtz <brvphoenix@gmail.com>

### OpenWrt Version

SNAPSHOT 

### OpenWrt Target/Subtarget

X86 

### Steps to Reproduce

Just build sing-box-full on a current Snapshot with only Go 1.27 available

### Actual Behaviour

Building sing-box (full variant, v1.13.18) against a Go 1.27 host toolchain fails:

github.com/go-json-experiment/json
../../../../../../dl/go-mod-cache/github.com/go-json-experiment/json@v0.0.0-20250813024750-ebf49471dced/alias.go:618:21: undefined: json.SkipFunc
../../../../../../dl/go-mod-cache/github.com/go-json-experiment/json@v0.0.0-20250813024750-ebf49471dced/alias.go:957:14: undefined: json.DiscardUnknownMembers

Cause: Go 1.27 removed several encoding/json/v2 APIs that go-json-experiment/json (a sing-box dependency) still relies on — specifically json.SkipFunc and json.DiscardUnknownMembers (see https://go.dev/doc/go1.27 and golang/go#77271). Several other Go projects (dagu, trivy) have hit the same break and worked around it by pinning to Go 1.26 until upstream catches up.

I also added Golang 1.26 again and pinned sing-box to it in the Makefile to get it compiled

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

### PR DESCRIPTION
**Pull request by Ser9ei**
This updates sing-box to 1.13.21.

Release: https://github.com/SagerNet/sing-box/releases/tag/v1.13.21

## 📦 Package Details

**Maintainer:**  @brvphoenix 
---

## 🧪 Run Testing Details

- **OpenWrt Version:** 25.12.5*
- **OpenWrt Target/Subtarget:** mediatek/filogic
- **OpenWrt Device:** Xiaomi Mi Router AX3000T
*Packages were built using a snapshot of the master SDK.
---

## ✅ Formalities

- [x] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### If your PR contains a patch:

- [x] It can be applied using `git am`
- [x] It has been refreshed to avoid offsets, fuzzes, etc., using
  ```bash
  make package/<your-package>/refresh V=s
  ```
- [x] It is structured in a way that it is potentially upstreamable
<sub>(e.g., subject line, commit description, etc.)</sub>
<sub>We must try to upstream patches to reduce maintenance burden.</sub>

### CODE REVIEW

**Review by openwrt-ai — COMMENTED** [review]
Reviewed 1 new commit; no new issues found.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by Ser9ei** [comment]
@hnyman, would you please merge this update?
