### PR TITLE
Update domoticz to version 4.10717

### PR DESCRIPTION
**Pull request by BKPepe**
Maintainer: @stintel 
Compile tested: Turris 1.1, powerpc_8540, OpenWrt 19.07.8
Run tested: Turris 1.1, powerpc_8540, OpenWrt 19.07.8 + domoticz starts also by running procd script, WebUI works.

Description:

- Fixes: https://github.com/openwrt/packages/issues/17453
- Cherry-picked from:
  - https://github.com/openwrt/packages/pull/9332
  - https://github.com/openwrt/packages/commit/7e50722145943e36bb687bc7462f8e483c8652b6

### CODE REVIEW

**Comment by BKPepe** [comment]
Log while running domoticz manually:
```
root@turris:~# domoticz
2021-12-29 22:04:26.473  Status: Domoticz V4.10717 (c)2012-2019 GizMoCuz
2021-12-29 22:04:26.474  Status: Build Hash: b97777b, Date: 2019-05-10 09:37:55
2021-12-29 22:04:26.474  Status: Startup Path: /usr/bin/
2021-12-29 22:04:26.688  Status: PluginSystem: Started, Python version '3.7.12'.
2021-12-29 22:04:26.698  Active notification Subsystems: gcm, http (2/13)
2021-12-29 22:04:26.700  Status: WebServer(HTTP) started on address: :: with port 8080
2021-12-29 22:04:26.703  Error: [web:443] missing SSL certificate chain file ./server_cert.pem!
2021-12-29 22:04:26.704  Error: [web:443] missing SSL certificate file ./server_cert.pem!
2021-12-29 22:04:26.704  Error: [web:443] missing SSL private key file ./server_cert.pem!
2021-12-29 22:04:26.705  Error: [web:443] missing SSL DH parameters file ./server_cert.pem!
2021-12-29 22:04:26.705  Status: WebServer(SSL) started on address: :: with port 443
2021-12-29 22:04:26.710  Starting shared server on: :::6144
2021-12-29 22:04:26.711  Status: RxQueue: queue worker started...
2021-12-29 22:04:26.712  Status: TCPServer: shared server started...
2021-12-29 22:04:28.713  Status: EventSystem: reset all events...
2021-12-29 22:04:28.714  Status: EventSystem: reset all device statuses...
2021-12-29 22:04:28.882  Status: Python EventSystem: Initalizing event module.
2021-12-29 22:04:28.882  Status: EventSystem: Started
2021-12-29 22:04:28.883  Status: EventSystem: Queue thread started...
2021-12-29 22:04:29.005  Status: PluginSystem: Entering work loop.
2021-12-29 22:04:32.998  Status: Incoming Domoticz connection from: XXX.XXX.X.XXX
```

Log when domoticz started via procd
```
Dec 29 22:05:03 turris domoticz: Domoticz is starting up....
Dec 29 22:05:03 turris domoticz: Domoticz running...
Dec 29 22:05:04 turris domoticz: Active notification Subsystems: gcm, http (2/13)
Dec 29 22:05:04 turris domoticz: Starting shared server on: :::6144
```

**Comment by stintel** [comment]
I am no longer using nor maintaining domoticz.

**Comment by BKPepe** [comment]
So, let's try to summon here @dwmw2, who took over the maintainership of this package.

**Comment by neheb** [comment]
CI failing on boost. I had patches that fixed compilation with uClibc-ng but never backported. No idea if @ClaymorePT wants to take a crack at it.

**Comment by ClaymorePT** [comment]
I will have to take a look at those patches. Van you pinpoint them for me
@neheb ?

**Comment by neheb** [comment]
it was backported as part of https://github.com/openwrt/packages/commit/c8907926cc32d504ba474d89437e4af5146cd214

**Comment by ClaymorePT** [comment]
@neheb It seems that the patches for uCli-ng which we added for Boost.Math in https://github.com/openwrt/packages/pull/10843 were also added upstream.

**Comment by neheb** [comment]
Right. This is for 19.07, which has an older boost version.

**Comment by ClaymorePT** [comment]
Ah right. Yeah, I believe I can do something about this. Let me work on that.

**Comment by ClaymorePT** [comment]
@neheb I'm confused. 19.07 has the math patches which were added by you  -> https://github.com/openwrt/packages/blob/openwrt-19.07/libs/boost/patches/004-uclibc-math.patch

What am I missing here?

**Comment by neheb** [comment]
oh hillarious. I thought it was a boost problem. The actual issue is:

```
2021-12-29T23:33:24.0927554Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:147:47: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0929297Z   result.DaylengthMins = static_cast<int>(std::round(modf(daylen, &_tmpH)*60));
2021-12-29T23:33:24.0934872Z                                                ^~~~~
2021-12-29T23:33:24.0937076Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:147:47: note: suggested alternative: 'count'
2021-12-29T23:33:24.0938871Z   result.DaylengthMins = static_cast<int>(std::round(modf(daylen, &_tmpH)*60));
2021-12-29T23:33:24.0939848Z                                                ^~~~~
2021-12-29T23:33:24.0940454Z                                                count
2021-12-29T23:33:24.0942144Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:157:47: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0943879Z   result.SunAtSouthMin = static_cast<int>(std::round(modf((rise+set)/2.0, &_tmpH)*60));
2021-12-29T23:33:24.0944873Z                                                ^~~~~
2021-12-29T23:33:24.0946578Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:157:47: note: suggested alternative: 'count'
2021-12-29T23:33:24.0948371Z   result.SunAtSouthMin = static_cast<int>(std::round(modf((rise+set)/2.0, &_tmpH)*60));
2021-12-29T23:33:24.0949367Z                                                ^~~~~
2021-12-29T23:33:24.0949953Z                                                count
2021-12-29T23:33:24.0951628Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:162:46: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0953535Z     result.SunRiseMin = static_cast<int>(std::round(modf(rise, &_tmpH)*60));
2021-12-29T23:33:24.0954460Z                                               ^~~~~
2021-12-29T23:33:24.0956195Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:162:46: note: suggested alternative: 'count'
2021-12-29T23:33:24.0957870Z     result.SunRiseMin = static_cast<int>(std::round(modf(rise, &_tmpH)*60));
2021-12-29T23:33:24.0958777Z                                               ^~~~~
2021-12-29T23:33:24.0959359Z                                               count
2021-12-29T23:33:24.0960985Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:164:45: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0962147Z     result.SunSetMin = static_cast<int>(std::round(modf(set, &_tmpH)*60));
2021-12-29T23:33:24.0962779Z                                              ^~~~~
2021-12-29T23:33:24.0964018Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:164:45: note: suggested alternative: 'count'
2021-12-29T23:33:24.0965226Z     result.SunSetMin = static_cast<int>(std::round(modf(set, &_tmpH)*60));
2021-12-29T23:33:24.0965865Z                                              ^~~~~
2021-12-29T23:33:24.0966299Z                                              count
2021-12-29T23:33:24.0974302Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:192:57: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0975682Z     result.CivilTwilightStartMin = static_cast<int>(std::round(modf(civ_start, &_tmpH)*60));
2021-12-29T23:33:24.0976761Z                                                          ^~~~~
2021-12-29T23:33:24.0978037Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:192:57: note: suggested alternative: 'count'
2021-12-29T23:33:24.0979442Z     result.CivilTwilightStartMin = static_cast<int>(std::round(modf(civ_start, &_tmpH)*60));
2021-12-29T23:33:24.0980315Z                                                          ^~~~~
2021-12-29T23:33:24.0980757Z                                                          count
2021-12-29T23:33:24.0981980Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:194:55: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0983296Z     result.CivilTwilightEndMin = static_cast<int>(std::round(modf(civ_end, &_tmpH)*60));
2021-12-29T23:33:24.0984091Z                                                        ^~~~~
2021-12-29T23:33:24.0985343Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:194:55: note: suggested alternative: 'count'
2021-12-29T23:33:24.0986688Z     result.CivilTwilightEndMin = static_cast<int>(std::round(modf(civ_end, &_tmpH)*60));
2021-12-29T23:33:24.0987499Z                                                        ^~~~~
2021-12-29T23:33:24.0987954Z                                                        count
2021-12-29T23:33:24.0989162Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:211:60: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0990587Z     result.NauticalTwilightStartMin = static_cast<int>(std::round(modf(naut_start, &_tmpH)*60));
2021-12-29T23:33:24.0991487Z                                                             ^~~~~
2021-12-29T23:33:24.0992734Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:211:60: note: suggested alternative: 'count'
2021-12-29T23:33:24.0994209Z     result.NauticalTwilightStartMin = static_cast<int>(std::round(modf(naut_start, &_tmpH)*60));
2021-12-29T23:33:24.0995112Z                                                             ^~~~~
2021-12-29T23:33:24.0995566Z                                                             count
2021-12-29T23:33:24.0996797Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:213:58: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.0998286Z     result.NauticalTwilightEndMin = static_cast<int>(std::round(modf(naut_end, &_tmpH)*60));
2021-12-29T23:33:24.0999158Z                                                           ^~~~~
2021-12-29T23:33:24.1000398Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:213:58: note: suggested alternative: 'count'
2021-12-29T23:33:24.1001815Z     result.NauticalTwilightEndMin = static_cast<int>(std::round(modf(naut_end, &_tmpH)*60));
2021-12-29T23:33:24.1002680Z                                                           ^~~~~
2021-12-29T23:33:24.1003129Z                                                           count
2021-12-29T23:33:24.1004348Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:230:64: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.1005835Z     result.AstronomicalTwilightStartMin = static_cast<int>(std::round(modf(astr_start, &_tmpH)*60));
2021-12-29T23:33:24.1006824Z                                                                 ^~~~~
2021-12-29T23:33:24.1008082Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:230:64: note: suggested alternative: 'count'
2021-12-29T23:33:24.1009866Z     result.AstronomicalTwilightStartMin = static_cast<int>(std::round(modf(astr_start, &_tmpH)*60));
2021-12-29T23:33:24.1011019Z                                                                 ^~~~~
2021-12-29T23:33:24.1011491Z                                                                 count
2021-12-29T23:33:24.1012826Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:232:62: error: 'round' is not a member of 'std'
2021-12-29T23:33:24.1014333Z     result.AstronomicalTwilightEndMin = static_cast<int>(std::round(modf(astr_end, &_tmpH)*60));
2021-12-29T23:33:24.1015278Z                                                               ^~~~~
2021-12-29T23:33:24.1016529Z /home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717/main/SunRiseSet.cpp:232:62: note: suggested alternative: 'count'
2021-12-29T23:33:24.1018014Z     result.AstronomicalTwilightEndMin = static_cast<int>(std::round(modf(astr_end, &_tmpH)*60));
2021-12-29T23:33:24.1018956Z                                                               ^~~~~
2021-12-29T23:33:24.1019422Z                                                               count
2021-12-29T23:33:24.2176515Z make[5]: *** [CMakeFiles/domoticz.dir/build.make:323: CMakeFiles/domoticz.dir/main/SunRiseSet.cpp.o] Error 1
2021-12-29T23:33:24.2185914Z make[5]: Leaving directory '/home/build/openwrt/build_dir/target-arc_archs_uClibc/domoticz-4.10717'
2021-12-29T23:33:24.2187148Z make[4]: *** [CMakeFiles/Makefile2:87: CMakeFiles/domoticz.dir/all] Error 2
```

Upstream patch: https://github.com/domoticz/domoticz/commit/01d0b036179e12284880fb2d29ae579399e5fe91

**Comment by BKPepe** [comment]
Thanks! Backported.

**Comment by dwmw2** [comment]
If we're updating anyway, is there any reason not to go all the way to 2021.1?

**Comment by BKPepe** [comment]
I suggested updating it to the next version, which was merged here. Because the current version does not work with Python 3.7. The next version remains to be config compatible, preventing any major API changes. That's why I didn't propose the update to the latest available version. It could bring unwanted issues to OpenWrt 19.07, which should receive security fixes and various bug fixes.

We need to keep in my that we are talking here about going here from version 4.9700 to 2021.1, where are huge changes. Not sure, if we want to bring it to the stable release. Who's is going to support it? I am not using domoticz on daily basis.

But you have the final word as you are the maintainer of domoticz.

**Comment by dwmw2** [comment]
Well, my production Domoticz (on OpenWrt 19.07 at the moment) is version 2020.1 anyway, so I'm already not running what's packaged. I'm all for upgrading all the way to 2021.1 if it's feasible to make that build (without having to upgrade boost, etc.)

**Comment by BKPepe** [comment]
2021.1:
```
/build/build_dir/target-powerpc_8540_musl/domoticz-2021.1 )
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.16.0 or higher is required.  You are running version 3.15.1
```

I'm going to try 2020.1

**Comment by BKPepe** [comment]
Well, even version 2020.1 can not be compiled for OpenWrt 19.07. By default, there is used cmake version 3.15 and it requires 3.16.  :(  I am not sure, if we want to update cmake as it could raise potential issues.
