### ISSUE TITLE
sing-box-full fails to build with Go 1.27: undefined: json.SkipFunc, json.DiscardUnknownMembers

### ISSUE THREAD

**Issue by egc112** [openwrt/packages#30423]
### Package Name

sing-box

### Maintainer

Van Waholtz <brvphoenix@gmail.com>

### OpenWrt Version

SNAPSHOT 

### OpenWrt Target/Subtarget

X86 

### Steps to Reproduce

Just build sing-box-full on a current Snapshot with only Go 1.27 available

### Actual Behaviour

Building sing-box (full variant, v1.13.18) against a Go 1.27 host toolchain fails:

github.com/go-json-experiment/json
../../../../../../dl/go-mod-cache/github.com/go-json-experiment/json@v0.0.0-20250813024750-ebf49471dced/alias.go:618:21: undefined: json.SkipFunc
../../../../../../dl/go-mod-cache/github.com/go-json-experiment/json@v0.0.0-20250813024750-ebf49471dced/alias.go:957:14: undefined: json.DiscardUnknownMembers

Cause: Go 1.27 removed several encoding/json/v2 APIs that go-json-experiment/json (a sing-box dependency) still relies on — specifically json.SkipFunc and json.DiscardUnknownMembers (see https://go.dev/doc/go1.27 and golang/go#77271). Several other Go projects (dagu, trivy) have hit the same break and worked around it by pinning to Go 1.26 until upstream catches up.

I also added Golang 1.26 again and pinned sing-box to it in the Makefile to get it compiled

### Confirmation Checklist

- [x] The package is maintained in this repository.
- [x] I understand that issues related to [the base OpenWrt repository](https://github.com/openwrt/openwrt/issues) or [LuCI repository](https://github.com/openwrt/luci/issues) will be closed.
- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by Ser9ei** [comment]
Homebrew already pinned to go@1.26 for the same issue:
https://github.com/Homebrew/homebrew-core/pull/300128

@GeorgeSapkin, would it be OK to restore golang1.26 as a versioned package in master (so we can pin sing-box to it, and possibly others)?

**Comment by GeorgeSapkin** [comment]
I don't think it makes sense to add previous versions of packages to a development branch, because a few other packages that depend on them don't build. This is an unavoidable situation (see GCC or CMake updates in the past) and it's up to those projects to figure this out.

**Comment by Ser9ei** [comment]
https://github.com/openwrt/packages/pull/30440
