### PR TITLE
python-cffi: update to latest version

### PR DESCRIPTION
**Pull request by jefferyto**
Signed-off-by: Jeffery To <jeffery.to@gmail.com>

### CODE REVIEW

**Comment by hnyman** [comment]
@jefferyto 
Buildbot is finally coming back up after four week's absence, and seems to be running into trouble with the python-cffi host compile:

    fatal error: pyconfig.h: No such file or directory

http://buildbot.openwrt.org:8010/builders/ar71xx.mikrotik/builds/163/steps/compile_5/logs/stdio
```
building '_cffi_backend' extension
creating build/temp.linux2-2.7
creating build/temp.linux2-2.7/c
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O2 -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/host/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/host/usr/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/target-mips_34kc_musl-1.1.14/host/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/host/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/host/usr/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/target-mips_34kc_musl-1.1.14/host/include -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/target-mips_34kc_musl-1.1.14/host/usr/include/python2.7 -fPIC -DUSE__THREAD -I/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/target-mips_34kc_musl-1.1.14/host/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux2-2.7/c/_cffi_backend.o
In file included from c/_cffi_backend.c:2:0:
/home/buildbot/slave/ar71xx.mikrotik/build/staging_dir/target-mips_34kc_musl-1.1.14/host/usr/include/python2.7/Python.h:8:22: fatal error: pyconfig.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
make[2]: *** [/home/buildbot/slave/ar71xx.mikrotik/build/build_dir/target-mips_34kc_musl-1.1.14/host/cffi-1.5.0/.built] Error 1
make[2]: Leaving directory `/home/buildbot/slave/ar71xx.mikrotik/build/feeds/packages/lang/python-cffi'
make[1]: *** [package/feeds/packages/python-cffi/host/compile] Error 2
```
As that failure is in the host tools section, it seems to break the whole buildbot run :-(

**Comment by hnyman** [comment]
I marked python-cffi as broken with https://github.com/openwrt/packages/commit/d43df25b1f3d2ef811f10d4f3297c6c42624b2f4 so the next buildbot run will not stop due to this package.

As there have been no buildbot builds for a month, the breakage could be due to the 1.4.2->1.5.0 version update, but it might also be due to path changes in e.g. https://github.com/openwrt/packages/commit/9f8e5aca342c806d1031e063b00a0045e0eb6c57 and https://github.com/openwrt/packages/commit/2140d8f6d24969d36faff000b96aee7a3b9f6aba . These python submodules seem to have so complex installation logic, that it is no wonder if some path gets handled wrong by a Makefile or host tool.

**Comment by jefferyto** [comment]
Thanks for your help @hnyman :smile:

Turns out Python installs its header files in `$(prefix)/include`, except for `pyconfig.h` which it puts in `$(exec-prefix)/include` (see https://bugs.python.org/issue896330), and `prefix` and `exec-prefix` diverged for host Python since c5564133.

I'm considering how to best solve this and hope to have a solution soon.

**Comment by commodo** [comment]
We could revert that commit.
I have no strong opinions about it.

**Comment by jefferyto** [comment]
@commodo I'm not sure it would be as simple as reverting that one commit - there has been a few changes that followed.

**Comment by commodo** [comment]
Well, not the entire commit.
Just the required bits.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Jeffery To <notifications@github.com> </div><div>Date:04/03/2016  12:40  (GMT+02:00) </div><div>To: openwrt/packages <packages@noreply.github.com> </div><div>Cc: Alexandru Ardelean <ardeleanalex@gmail.com> </div><div>Subject: Re: [packages] python-cffi: update to latest version (#2360) </div><div>
</div>@commodo I'm not sure it would be as simple as reverting that one commit - there has been a few changes that followed.

**Comment by jefferyto** [comment]
#2455 should fix this issue. I've done a few test compiles but please double-check.

Cryptography 1.2.2 still won't compile after these changes though; #2456 updates it to 1.2.3 which should compile.

**Comment by hnyman** [comment]
I removed the BROKEN status from python-cffi with https://github.com/openwrt/packages/commit/183850e15fd3d99260bf1eea5c142912e71fc868

I tested compiling myself, and both -cffi and -cryptography compiled ok locally.

Additionally r48918 has decreased the risk from failing host sections to buildbot builds. One failing non-core package should not stop the whole build any more: https://dev.openwrt.org/changeset/48918
