### PR TITLE
luasql: fix compile with mariadb-10.2.x

### PR DESCRIPTION
**Pull request by micmac1**
This is in anticipation of the mariadb upgrade to 10.2.x. luasql compile
fails:

```
In file included from src/ls_mysql.c:21:0:
src/ls_mysql.c: In function 'luaopen_luasql_mysql':
src/ls_mysql.c:605:25: error: expected ')' before 'MYSQL_SERVER_VERSION'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
                         ^
src/ls_mysql.c:605:5: error: too few arguments to function 'lua_pushlstring'
     lua_pushliteral (L, MYSQL_SERVER_VERSION);
     ^
/home/equeiroz/src/openwrt-asus/staging_dir/target-mipsel_74kc_musl/usr/include/lua.h:175:16: note: declared here
 LUA_API void  (lua_pushlstring) (lua_State *L, const char *s, size_t l);
                ^~~~~~~~~~~~~~~
```

To fix this cherry-pick upstream commit
6df3f672313f8dbca219199c8ec8d20c0247347f.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

Maintainer: @psycho-nico 
Compile tested: ar71xx
Run tested: N/A

Description:
Hello @psycho-nico 

Please consider this pull request. We're working in pull requst #6301  on upgrading mariadb in master from 10.1.x to 10.2.x, @cotequeiroz found that the current luasql version does not compile against mariadb 10.2.x.

I have not run-tested this and as I don't know much about lua I won't be able to. But as this is just about a variable I don't expect any issue.

Thanks!
Seb

### CODE REVIEW

**Comment by karlp** [comment]
merged in c9a9f6f9 thanks.
