### ISSUE TITLE
ulogd fails to build on arch with Kernel 3.18 (oxnas)(buildbot)

### ISSUE THREAD

**Issue by plntyk** [openwrt/packages#908]
Error:
```
In file included from libipulog.c:31:0:
../include/libipulog/libipulog.h:13:43: fatal error: linux/netfilter_ipv4/ipt_ULOG.h: No such file or directory
 #include <linux/netfilter_ipv4/ipt_ULOG.h>
```
http://buildbot.openwrt.org:8010/broken_packages/oxnas/ulogd/compile.txt
reported by buildbot

Caused by issue: ulogd is removed in Kernel 3.17 upstream

Fix: upstream git has a fix
http://git.netfilter.org/ulogd2/commit/?id=30e24dbfc7a8644e29664070e8c16e5c3997f87e

@psycho-nico

**Comment by dangowrt** [comment]
fixed by https://github.com/openwrt/packages/commit/ce83241311758402d9ecffe191e51db81f29c76e
Thanks for reporting!
