### PR TITLE
domoticz: fix build and add test.sh

### PR DESCRIPTION
**Pull request by commodo**
## 📦 Package Details

**Maintainer:**  @dwmw2

**Description:**

boost::asio::post() without an explicit executor fails to compile with Boost >= 1.82 due to changes in the executor model: bare lambdas no longer have an implicit system executor that satisfies the blocking.never requirement.

Pass io_context_ explicitly as the first argument so the handler is dispatched on the correct io_context thread, which is the original intent of the call (making stop() safe to call from any thread).

Add test.sh
domoticz is a daemon requiring a database and network port; it does not implement a --version flag. Verify the binary is present and executable.

Disable LTO to fix link failure on i386 with musl fortify Suggested via https://github.com/openwrt/packages/pull/29239 Also tested.

---

## 🧪 Run Testing Details

- **OpenWrt Version:**
- **OpenWrt Target/Subtarget:**
- **OpenWrt Device:**

---

## ✅ Formalities

- [ ] I have reviewed the [CONTRIBUTING.md](https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### If your PR contains a patch:

- [ ] It can be applied using `git am`
- [ ] It has been refreshed to avoid offsets, fuzzes, etc., using
  ```bash
  make package/<your-package>/refresh V=s
  ```
- [ ] It is structured in a way that it is potentially upstreamable
<sub>(e.g., subject line, commit description, etc.)</sub>
<sub>We must try to upstream patches to reduce maintenance burden.</sub>

### CODE REVIEW

**Comment by GeorgeSapkin** [comment]
Generic tests are now forced for all packages, irrespective of `test.sh` presence. If this one can't pass the generic tests, then they need to be adjusted to accommodate this scenario. Let's see what the CI says first.

**Comment by commodo** [comment]
> Generic tests are now forced for all packages, irrespective of `test.sh` presence. If this one can't pass the generic tests, then they need to be adjusted to accommodate this scenario. Let's see what the CI says first.

Two failures stand-out.
One in boost, where libquadmath is not present on all archs.
And another on openzwave where `openzwave: No executables in the package provided version 1.6.1965`

**Comment by GeorgeSapkin** [comment]
Also for some reason `file` is gone half way. And GH is crapping out as usual, so I can't pull the logs to see what's up.

**Comment by GeorgeSapkin** [comment]
liblzma is purging file:

```
 (1/4) Purging file (5.45-r1)
  Executing file-5.45-r1.pre-deinstall
```

I guess `apk del --rdepends` is a no-go.

**Comment by GeorgeSapkin** [comment]
Pushed to the wrong repo. Sorry.
