### PR TITLE
openvswitch: fix build with kernel >= 3.18.13

### LINKED ISSUE #1283: openvswitch compile error
^
In file included from /home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux/actions.c:30:0:
/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux/compat/include/linux/if_vlan.h:83:31: error: redefinition of 'vlan_hwaccel_push_inside'
 static inline struct sk_buff *vlan_hwaccel_push_inside(struct sk_buff *skb)
                               ^
In file included from /home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux/compat/include/linux/if_vlan.h:6:0,
                 from /home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux/actions.c:30:
include/linux/if_vlan.h:371:31: note: previous definition of 'vlan_hwaccel_push_inside' was here
 static inline struct sk_buff *vlan_hwaccel_push_inside(struct sk_buff *skb)
                               ^
make[8]: *** [/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux/actions.o] Error 1
make[7]: *** [_module_/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux] Error 2
make[7]: Leaving directory `/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/linux-x86_64/linux-3.18.14'
make[6]: *** [default] Error 2
make[6]: Leaving directory `/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/datapath/linux'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90'
make[4]: *** [all] Error 2
make[4]: Leaving directory `/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90'
make[3]: *** [/home/main/openwrt/build_dir/target-x86_64_uClibc-0.9.33.2/openvswitch-2.3.90/.built] Error 2
make[3]: Leaving directory `/home/main/openwrt/feeds/packages/net/openvswitch'
make[2]: *** [package/feeds/packages/openvswitch/compile] Error 2
make[2]: Leaving directory `/home/main/openwrt'
make[1]: *** [/home/main/openwrt/staging_dir/target-x86_64_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/main/openwrt'
make: *** [world] Error 2

### PR DESCRIPTION
**Pull request by hauke**
This fixes a build problem with kernel >= 3.18.13.
This should close #1283.

Signed-off-by: Hauke Mehrtens <hauke@hauke-m.de>

### CODE REVIEW

**Comment by commodo** [comment]
+1
thanks for fixing this; was going to look at this on Monday;

**Comment by thess** [comment]
I think this requires a PKG_RELEASE change?

**Comment by sbyx** [comment]
@hauke Feel free to merge and please backport to for-15.05, also as thess noted, maybe bump PKG_REVISION as well.

**Comment by hauke** [comment]
pushed directly
